#!/usr/bin/env bash
# system.sh — timezone, locale, hostname, keymap, fstab, users, finalization
# Alpine Linux uses OpenRC init system
source "${LIB_DIR}/protection.sh"

# --- Timezone ---

system_set_timezone() {
    local tz="${TIMEZONE:-UTC}"
    einfo "Setting timezone: ${tz}"

    # Install tzdata (not in alpine-base by default)
    apk_install "Installing timezone data" tzdata

    try "Setting timezone" \
        chroot_exec "ln -sf /usr/share/zoneinfo/${tz} /etc/localtime"

    # Write timezone to /etc/timezone for OpenRC
    chroot_exec "echo '${tz}' > /etc/timezone"

    # Hardware clock (UTC by default, localtime for dual-boot with Windows)
    if [[ "${WINDOWS_DETECTED:-0}" == "1" ]]; then
        chroot_exec "sed -i 's/^clock=.*/clock=\"local\"/' /etc/conf.d/hwclock 2>/dev/null || echo 'clock=\"local\"' > /etc/conf.d/hwclock"
        ewarn "Hardware clock set to localtime for Windows dual-boot"
    fi
}

# --- Locale ---

system_set_locale() {
    local locale="${LOCALE:-en_US.UTF-8}"
    einfo "Setting locale: ${locale}"

    # /etc/profile.d/locale.sh — main locale config for Alpine (musl-based)
    chroot_exec "mkdir -p /etc/profile.d"
    chroot_exec "cat > /etc/profile.d/locale.sh << LOCEOF
export LANG=${locale}
export LC_ALL=${locale}
LOCEOF"
    chroot_exec "chmod +x /etc/profile.d/locale.sh"

    # Install musl-locales for locale data (musl has minimal built-in locale support)
    apk_install_if_available musl-locales
    apk_install_if_available musl-locales-lang

    einfo "Locale set to ${locale}"
}

# --- Hostname ---

system_set_hostname() {
    local hostname="${HOSTNAME:-alpine}"

    # Validate hostname (RFC 1123)
    if [[ ! "${hostname}" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$ ]]; then
        ewarn "Invalid hostname '${hostname}', falling back to 'alpine'"
        hostname="alpine"
    fi

    einfo "Setting hostname: ${hostname}"

    chroot_exec "echo '${hostname}' > /etc/hostname"

    # Update /etc/hosts
    chroot_exec "cat > /etc/hosts << HOSTSEOF
# /etc/hosts
127.0.0.1   localhost
::1         localhost
127.0.1.1   ${hostname}.localdomain ${hostname}
HOSTSEOF"
}

# --- Keymap ---

system_set_keymap() {
    local keymap="${KEYMAP:-us}"
    einfo "Setting keymap: ${keymap}"

    # Install kbd for loadkeys
    apk_install_if_available kbd-bkeymaps

    # Alpine uses /etc/conf.d/loadkmap for console keymap
    chroot_exec "mkdir -p /etc/conf.d"

    # Set keymap for OpenRC loadkmap service
    if chroot_exec "test -d /usr/share/bkeymaps/${keymap}" 2>/dev/null; then
        chroot_exec "cat > /etc/conf.d/loadkmap << 'KBEOF'
KEYMAP=${keymap}/${keymap}.bmap.gz
KBEOF"
    else
        chroot_exec "cat > /etc/conf.d/loadkmap << 'KBEOF'
KEYMAP=us/us.bmap.gz
KBEOF"
    fi

    # Enable loadkmap service
    chroot_exec "rc-update add loadkmap boot" 2>/dev/null || true

    # Also set Xorg/Wayland keymap via /etc/X11/xorg.conf.d or environment
    chroot_exec "mkdir -p /etc/X11/xorg.conf.d"
    chroot_exec "cat > /etc/X11/xorg.conf.d/00-keyboard.conf << XKBEOF
Section \"InputClass\"
    Identifier \"keyboard-all\"
    MatchIsKeyboard \"on\"
    Option \"XkbLayout\" \"${keymap}\"
    Option \"XkbModel\" \"pc105\"
EndSection
XKBEOF"
}

# --- fstab ---

generate_fstab() {
    einfo "Generating /etc/fstab..."

    if [[ "${DRY_RUN}" == "1" ]]; then
        einfo "[DRY-RUN] Would generate fstab"
        return 0
    fi

    # Manual fstab generation (Alpine doesn't have genfstab)
    _generate_fstab_manual

    einfo "fstab generated"
}

# --- crypttab ---

generate_crypttab() {
    if [[ "${LUKS_ENABLED:-no}" != "yes" ]]; then
        return 0
    fi

    einfo "Generating /etc/crypttab..."

    local luks_uuid
    luks_uuid=$(get_uuid "${LUKS_PARTITION}")

    if [[ -z "${luks_uuid}" ]]; then
        eerror "Cannot determine UUID for LUKS partition ${LUKS_PARTITION}"
        return 1
    fi

    echo "cryptroot UUID=${luks_uuid} none luks" > "${MOUNTPOINT}/etc/crypttab"

    einfo "crypttab generated for ${LUKS_PARTITION} (UUID=${luks_uuid})"
}

_generate_fstab_manual() {
    local fstab="${MOUNTPOINT}/etc/fstab"
    local fs="${FILESYSTEM:-ext4}"

    {
        echo "# /etc/fstab"
        echo "# Generated by ${INSTALLER_NAME} v${INSTALLER_VERSION}"
        echo "#"
        echo "# <fs>                                  <mountpoint>  <type>  <opts>                                  <dump/pass>"

        # Root filesystem
        local root_dev="${ROOT_PARTITION}"
        if [[ "${LUKS_ENABLED:-no}" == "yes" ]]; then
            root_dev="/dev/mapper/cryptroot"
        fi
        local root_uuid
        root_uuid=$(get_uuid "${root_dev}")

        if [[ -n "${root_uuid}" ]]; then
            case "${fs}" in
                btrfs)
                    echo "UUID=${root_uuid}   /             btrfs   subvol=@,compress=zstd,noatime,defaults  0 1"
                    if [[ -n "${BTRFS_SUBVOLUMES:-}" ]]; then
                        local IFS=':'
                        local -a parts
                        read -ra parts <<< "${BTRFS_SUBVOLUMES}"
                        local idx
                        for (( idx = 0; idx < ${#parts[@]}; idx += 2 )); do
                            local subvol="${parts[$idx]}"
                            local mpoint="${parts[$((idx + 1))]}"
                            [[ "${subvol}" == "@" ]] && continue
                            echo "UUID=${root_uuid}   ${mpoint}          btrfs   subvol=${subvol},compress=zstd,noatime,defaults  0 2"
                        done
                    fi
                    ;;
                ext4)
                    echo "UUID=${root_uuid}   /             ext4    noatime,defaults        0 1"
                    ;;
                xfs)
                    echo "UUID=${root_uuid}   /             xfs     noatime,defaults        0 1"
                    ;;
            esac
        else
            echo "${root_dev}              /             ${fs}     noatime,defaults        0 1"
        fi

        # ESP
        local esp_uuid
        esp_uuid=$(get_uuid "${ESP_PARTITION}")
        local esp_mount="/boot/efi"
        [[ "${BOOTLOADER_TYPE:-grub}" == "systemd-boot" ]] && esp_mount="/boot"

        if [[ -n "${esp_uuid}" ]]; then
            echo "UUID=${esp_uuid}   ${esp_mount}          vfat    noatime,defaults        0 2"
        else
            echo "${ESP_PARTITION}              ${esp_mount}          vfat    noatime,defaults        0 2"
        fi

        # Swap partition
        if [[ "${SWAP_TYPE:-}" == "partition" && -n "${SWAP_PARTITION:-}" ]]; then
            local swap_uuid
            swap_uuid=$(get_uuid "${SWAP_PARTITION}")
            if [[ -n "${swap_uuid}" ]]; then
                echo "UUID=${swap_uuid}   none          swap    sw              0 0"
            else
                echo "${SWAP_PARTITION}              none          swap    sw              0 0"
            fi
        fi

        echo "tmpfs                                   /tmp          tmpfs   defaults,nosuid,nodev   0 0"

    } > "${fstab}"
}

# --- Kernel ---

kernel_install() {
    local kernel_type="${KERNEL_TYPE:-lts}"
    einfo "Installing kernel: linux-${kernel_type}"

    case "${kernel_type}" in
        lts)
            apk_install "Installing LTS kernel" linux-lts
            ;;
        edge)
            apk_install "Installing edge kernel" linux-edge
            ;;
    esac

    # Install firmware meta-package
    apk_install "Installing firmware" linux-firmware

    # CPU microcode
    local ucode_pkg
    ucode_pkg=$(get_microcode_package "${CPU_VENDOR:-}")
    if [[ -n "${ucode_pkg}" ]]; then
        apk_install "Installing CPU microcode" "${ucode_pkg}"
    fi

    # cryptsetup: required for initramfs to pick up /etc/crypttab (LUKS boot)
    if [[ "${LUKS_ENABLED:-no}" == "yes" ]]; then
        apk_install "Installing cryptsetup" cryptsetup

        # Configure mkinitfs features for LUKS
        local mkinitfs_conf="${MOUNTPOINT}/etc/mkinitfs/mkinitfs.conf"
        if [[ -f "${mkinitfs_conf}" ]]; then
            # Add cryptsetup feature if not already present
            if ! grep -q 'cryptsetup' "${mkinitfs_conf}" 2>/dev/null; then
                chroot_exec "sed -i 's/features=\"/features=\"cryptsetup /' /etc/mkinitfs/mkinitfs.conf"
            fi
        else
            chroot_exec "mkdir -p /etc/mkinitfs"
            chroot_exec "echo 'features=\"ata base ide scsi usb virtio ext4 cryptsetup keymap\"' > /etc/mkinitfs/mkinitfs.conf"
        fi
    fi

    # Generate initramfs using mkinitfs (Alpine's initramfs generator)
    try "Generating initramfs" \
        chroot_exec "mkinitfs"

    einfo "Kernel installed"
}

# --- Networking ---

install_networking() {
    einfo "Installing networking..."

    apk_install "Installing NetworkManager" networkmanager

    # Enable NetworkManager via OpenRC
    try "Enabling NetworkManager" \
        chroot_exec "rc-update add networkmanager default"

    # Disable default Alpine networking (ifupdown) to avoid conflicts
    chroot_exec "rc-update del networking default" 2>/dev/null || true

    einfo "Networking configured"
}

# --- Users ---

system_create_users() {
    einfo "Creating users..."

    # Install shadow for full useradd/chpasswd (busybox versions are limited)
    apk_install "Installing shadow" shadow

    # Set root password (chpasswd -e avoids exposing hash in process list)
    if [[ -n "${ROOT_PASSWORD_HASH:-}" ]]; then
        try "Setting root password" \
            chroot_exec "echo 'root:${ROOT_PASSWORD_HASH}' | chpasswd -e"
    fi

    # Create regular user
    if [[ -n "${USERNAME:-}" ]]; then
        local groups="${USER_GROUPS:-wheel,audio,video,input,plugdev}"

        # Filter out groups that don't exist on the target system
        local valid_groups=""
        local g
        IFS=',' read -ra _groups <<< "${groups}"
        for g in "${_groups[@]}"; do
            if chroot_exec "getent group ${g}" &>/dev/null; then
                valid_groups+="${valid_groups:+,}${g}"
            else
                # Try to create common groups that may not exist yet
                case "${g}" in
                    plugdev|input)
                        chroot_exec "addgroup ${g}" 2>/dev/null || true
                        valid_groups+="${valid_groups:+,}${g}"
                        ;;
                    *)
                        ewarn "Group '${g}' does not exist, skipping"
                        ;;
                esac
            fi
        done
        groups="${valid_groups:-wheel}"

        # Install bash and use it as login shell
        apk_install_if_available bash

        local user_shell="/bin/sh"
        if chroot_exec "test -x /bin/bash" 2>/dev/null; then
            user_shell="/bin/bash"
        fi

        try "Creating user ${USERNAME}" \
            chroot_exec "useradd -m -G ${groups} -s ${user_shell} ${USERNAME}"

        if [[ -n "${USER_PASSWORD_HASH:-}" ]]; then
            try "Setting user password" \
                chroot_exec "echo '${USERNAME}:${USER_PASSWORD_HASH}' | chpasswd -e"
        fi

        # Setup doas (Alpine uses doas by default, lighter than sudo)
        apk_install_if_available doas
        chroot_exec "mkdir -p /etc"
        chroot_exec "echo 'permit persist :wheel' > /etc/doas.d/wheel.conf"
        chroot_exec "chmod 0640 /etc/doas.d/wheel.conf"

        einfo "User ${USERNAME} created with groups: ${groups}"
    fi

    # SSH
    if [[ "${ENABLE_SSH:-no}" == "yes" ]]; then
        apk_install "Installing OpenSSH" openssh

        try "Enabling sshd" \
            chroot_exec "rc-update add sshd default"

        einfo "SSH server enabled"
    fi
}

# --- Finalization ---

system_finalize() {
    einfo "Finalizing system..."

    # Enable essential OpenRC services
    chroot_exec "rc-update add devfs sysinit" 2>/dev/null || true
    chroot_exec "rc-update add dmesg sysinit" 2>/dev/null || true
    chroot_exec "rc-update add mdev sysinit" 2>/dev/null || true
    chroot_exec "rc-update add hwdrivers sysinit" 2>/dev/null || true

    chroot_exec "rc-update add hwclock boot" 2>/dev/null || true
    chroot_exec "rc-update add modules boot" 2>/dev/null || true
    chroot_exec "rc-update add sysctl boot" 2>/dev/null || true
    chroot_exec "rc-update add hostname boot" 2>/dev/null || true
    chroot_exec "rc-update add bootmisc boot" 2>/dev/null || true
    chroot_exec "rc-update add syslog boot" 2>/dev/null || true

    chroot_exec "rc-update add mount-ro shutdown" 2>/dev/null || true
    chroot_exec "rc-update add killprocs shutdown" 2>/dev/null || true
    chroot_exec "rc-update add savecache shutdown" 2>/dev/null || true

    # Enable udev for proper device management (needed for desktop)
    if [[ "${DESKTOP_ENV:-none}" != "none" ]]; then
        apk_install_if_available eudev
        chroot_exec "setup-devd udev" 2>/dev/null || true
    fi

    # Generate machine-id
    chroot_exec "dbus-uuidgen --ensure=/etc/machine-id" 2>/dev/null || true

    # Set correct date/time inside chroot if possible
    chroot_exec "hwclock --systohc" 2>/dev/null || true

    # Install bundled gum binary (useful for dotfiles/scripts)
    if [[ -x "${GUM_CACHE_DIR:-/tmp/alpine-gum}/gum" ]]; then
        cp "${GUM_CACHE_DIR}/gum" "${MOUNTPOINT}/usr/local/bin/gum" 2>/dev/null && \
            chmod +x "${MOUNTPOINT}/usr/local/bin/gum" && \
            einfo "Installed gum to /usr/local/bin/gum"
    elif [[ -f "${DATA_DIR:-}/gum.tar.gz" ]]; then
        local _gum_tmp
        _gum_tmp=$(mktemp -d)
        if tar xzf "${DATA_DIR}/gum.tar.gz" -C "${_gum_tmp}" 2>/dev/null; then
            local _gum_bin
            _gum_bin=$(find "${_gum_tmp}" -name "gum" -type f | head -1)
            if [[ -n "${_gum_bin}" ]]; then
                cp "${_gum_bin}" "${MOUNTPOINT}/usr/local/bin/gum"
                chmod +x "${MOUNTPOINT}/usr/local/bin/gum"
                einfo "Installed gum to /usr/local/bin/gum"
            fi
        fi
        rm -rf "${_gum_tmp}"
    fi

    # Clean up installer artifacts from target disk
    rm -rf "${MOUNTPOINT}${CHECKPOINT_DIR_SUFFIX}" 2>/dev/null || true
    rm -f "${MOUNTPOINT}/tmp/$(basename "${CONFIG_FILE}")" 2>/dev/null || true

    einfo "System finalization complete"
}
