#!/usr/bin/env bash
# system.sh — timezone, locale, hostname, keymap, fstab, users, finalization
# Alpine Linux uses OpenRC init system
source "${LIB_DIR}/protection.sh"

# --- Timezone ---

system_set_timezone() {
    local tz="${TIMEZONE:-UTC}"

    # Validate timezone
    if [[ ! -f "/usr/share/zoneinfo/${tz}" ]]; then
        ewarn "Invalid timezone '${tz}', falling back to UTC"
        tz="UTC"
    fi

    einfo "Setting timezone: ${tz}"

    # Install tzdata (not in alpine-base by default)
    apk_install "Installing timezone data" tzdata

    try "Setting timezone" \
        chroot_exec "ln -sf /usr/share/zoneinfo/${tz} /etc/localtime"

    # Write timezone to /etc/timezone for OpenRC
    chroot_exec "echo '${tz}' > /etc/timezone"

    # Hardware clock (UTC by default, localtime for dual-boot with Windows)
    if [[ "${WINDOWS_DETECTED:-0}" == "1" ]]; then
        chroot_exec "sed -i 's/^clock=.*/clock=\"local\"/' /etc/conf.d/hwclock 2>/dev/null || echo 'clock=\"local\"' > /etc/conf.d/hwclock"
        ewarn "Hardware clock set to localtime for Windows dual-boot"
    fi
}

# --- Locale ---

system_set_locale() {
    local locale="${LOCALE:-en_US.UTF-8}"
    einfo "Setting locale: ${locale}"

    # /etc/profile.d/locale.sh — login-shell sessions (TTY, ssh).
    chroot_exec "mkdir -p /etc/profile.d"
    chroot_exec "cat > /etc/profile.d/locale.sh << LOCEOF
export LANG=${locale}
export LC_COLLATE=${locale}
LOCEOF"
    chroot_exec "chmod +x /etc/profile.d/locale.sh"

    # Display managers (SDDM/GDM/LightDM), greetd and elogind/PAM sessions do
    # NOT source a login shell, so /etc/profile.d alone leaves the GUI in the C
    # locale. /etc/locale.conf and /etc/environment are read by PAM/elogind and
    # apply to graphical sessions.
    chroot_exec "cat > /etc/locale.conf << LOCEOF
LANG=${locale}
LC_COLLATE=${locale}
LOCEOF"
    chroot_exec "cat > /etc/environment << ENVEOF
LANG=${locale}
LC_COLLATE=${locale}
ENVEOF"

    # Install musl-locales for locale data (musl has minimal built-in locale support)
    apk_install_if_available musl-locales
    apk_install_if_available musl-locales-lang

    einfo "Locale set to ${locale}"
}

# --- Hostname ---

system_set_hostname() {
    local hostname="${HOSTNAME:-alpine}"

    # Validate hostname (RFC 1123)
    if [[ ! "${hostname}" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$ ]]; then
        ewarn "Invalid hostname '${hostname}', falling back to 'alpine'"
        hostname="alpine"
    fi

    einfo "Setting hostname: ${hostname}"

    chroot_exec "echo '${hostname}' > /etc/hostname"

    # Update /etc/hosts
    chroot_exec "cat > /etc/hosts << HOSTSEOF
# /etc/hosts
127.0.0.1   localhost
::1         localhost
127.0.1.1   ${hostname}.localdomain ${hostname}
HOSTSEOF"
}

# --- Keymap ---

system_set_keymap() {
    local keymap="${KEYMAP:-us}"
    einfo "Setting keymap: ${keymap}"

    # Install kbd for loadkeys
    apk_install_if_available kbd-bkeymaps

    # Alpine uses /etc/conf.d/loadkmap for console keymap
    chroot_exec "mkdir -p /etc/conf.d"

    # Set keymap for OpenRC loadkmap service
    if chroot_exec "test -d /usr/share/bkeymaps/${keymap}" 2>/dev/null; then
        chroot_exec "cat > /etc/conf.d/loadkmap << 'KBEOF'
KEYMAP=${keymap}/${keymap}.bmap.gz
KBEOF"
    else
        chroot_exec "cat > /etc/conf.d/loadkmap << 'KBEOF'
KEYMAP=us/us.bmap.gz
KBEOF"
    fi

    # Enable loadkmap service
    chroot_exec "rc-update add loadkmap boot" 2>/dev/null || true

    # Also set Xorg/Wayland keymap via /etc/X11/xorg.conf.d or environment
    chroot_exec "mkdir -p /etc/X11/xorg.conf.d"
    chroot_exec "cat > /etc/X11/xorg.conf.d/00-keyboard.conf << XKBEOF
Section \"InputClass\"
    Identifier \"keyboard-all\"
    MatchIsKeyboard \"on\"
    Option \"XkbLayout\" \"${keymap}\"
    Option \"XkbModel\" \"pc105\"
EndSection
XKBEOF"
}

# --- fstab ---

generate_fstab() {
    einfo "Generating /etc/fstab..."

    if [[ "${DRY_RUN}" == "1" ]]; then
        einfo "[DRY-RUN] Would generate fstab"
        return 0
    fi

    # Manual fstab generation (Alpine doesn't have genfstab)
    _generate_fstab_manual

    einfo "fstab generated"
}

# --- crypttab ---

generate_crypttab() {
    if [[ "${LUKS_ENABLED:-no}" != "yes" ]]; then
        return 0
    fi

    einfo "Generating /etc/crypttab..."

    local luks_uuid
    luks_uuid=$(get_uuid "${LUKS_PARTITION}")

    if [[ -z "${luks_uuid}" ]]; then
        eerror "Cannot determine UUID for LUKS partition ${LUKS_PARTITION}"
        return 1
    fi

    echo "cryptroot UUID=${luks_uuid} none luks" > "${MOUNTPOINT}/etc/crypttab"

    einfo "crypttab generated for ${LUKS_PARTITION} (UUID=${luks_uuid})"
}

_generate_fstab_manual() {
    local fstab="${MOUNTPOINT}/etc/fstab"
    local fs="${FILESYSTEM:-ext4}"

    {
        echo "# /etc/fstab"
        echo "# Generated by ${INSTALLER_NAME} v${INSTALLER_VERSION}"
        echo "#"
        echo "# <fs>                                  <mountpoint>  <type>  <opts>                                  <dump/pass>"

        # Root filesystem
        local root_dev="${ROOT_PARTITION}"
        if [[ "${LUKS_ENABLED:-no}" == "yes" ]]; then
            root_dev="/dev/mapper/cryptroot"
        fi
        local root_uuid
        root_uuid=$(get_uuid "${root_dev}")

        if [[ -n "${root_uuid}" ]]; then
            case "${fs}" in
                btrfs)
                    echo "UUID=${root_uuid}   /             btrfs   subvol=@,compress=zstd,noatime,defaults  0 1"
                    if [[ -n "${BTRFS_SUBVOLUMES:-}" ]]; then
                        local IFS=':'
                        local -a parts
                        read -ra parts <<< "${BTRFS_SUBVOLUMES}"
                        local idx
                        for (( idx = 0; idx < ${#parts[@]}; idx += 2 )); do
                            local subvol="${parts[$idx]}"
                            local mpoint="${parts[$((idx + 1))]}"
                            [[ "${subvol}" == "@" ]] && continue
                            echo "UUID=${root_uuid}   ${mpoint}          btrfs   subvol=${subvol},compress=zstd,noatime,defaults  0 2"
                        done
                    fi
                    ;;
                ext4)
                    echo "UUID=${root_uuid}   /             ext4    noatime,defaults        0 1"
                    ;;
                xfs)
                    echo "UUID=${root_uuid}   /             xfs     noatime,defaults        0 1"
                    ;;
            esac
        else
            echo "${root_dev}              /             ${fs}     noatime,defaults        0 1"
        fi

        # ESP
        local esp_uuid
        esp_uuid=$(get_uuid "${ESP_PARTITION}")
        local esp_mount="/boot/efi"

        if [[ -n "${esp_uuid}" ]]; then
            echo "UUID=${esp_uuid}   ${esp_mount}          vfat    noatime,defaults        0 2"
        else
            echo "${ESP_PARTITION}              ${esp_mount}          vfat    noatime,defaults        0 2"
        fi

        # Swap partition
        if [[ "${SWAP_TYPE:-}" == "partition" && -n "${SWAP_PARTITION:-}" ]]; then
            local swap_uuid
            swap_uuid=$(get_uuid "${SWAP_PARTITION}")
            if [[ -n "${swap_uuid}" ]]; then
                echo "UUID=${swap_uuid}   none          swap    sw              0 0"
            else
                echo "${SWAP_PARTITION}              none          swap    sw              0 0"
            fi
        fi

        echo "tmpfs                                   /tmp          tmpfs   defaults,nosuid,nodev   0 0"

    } > "${fstab}"
}

# --- Kernel ---

kernel_install() {
    local kernel_type="${KERNEL_TYPE:-lts}"
    einfo "Installing kernel: linux-${kernel_type}"

    case "${kernel_type}" in
        lts)
            apk_install "Installing LTS kernel" linux-lts
            ;;
        edge)
            apk_install "Installing edge kernel" linux-edge
            ;;
        *)
            ewarn "Unknown kernel type '${kernel_type}', defaulting to linux-lts"
            kernel_type="lts"
            apk_install "Installing LTS kernel" linux-lts
            ;;
    esac

    # Linux firmware (Wi-Fi/GPU). The meta-package name may vary per branch, so
    # install it best-effort rather than failing the whole phase.
    apk_install_if_available linux-firmware

    # CPU microcode
    local ucode_pkg
    ucode_pkg=$(get_microcode_package "${CPU_VENDOR:-}")
    if [[ -n "${ucode_pkg}" ]]; then
        apk_install "Installing CPU microcode" "${ucode_pkg}"
    fi

    # cryptsetup is needed inside the initramfs for LUKS root.
    if [[ "${LUKS_ENABLED:-no}" == "yes" ]]; then
        apk_install "Installing cryptsetup" cryptsetup
    fi

    # mkinitfs.conf features. The stock default (base ata ide scsi usb virtio
    # ext4) cannot mount a btrfs/xfs root — the system would be unbootable.
    # Always declare the features matching the chosen filesystem, keymap (for
    # LUKS passphrase / console), and cryptsetup when encrypted.
    local features="base ata ide scsi usb virtio nvme mmc keymap kms"
    case "${FILESYSTEM:-ext4}" in
        btrfs) features+=" btrfs" ;;
        xfs)   features+=" xfs ext4" ;;
        *)     features+=" ext4" ;;
    esac
    [[ "${LUKS_ENABLED:-no}" == "yes" ]] && features+=" cryptsetup"

    chroot_exec "mkdir -p /etc/mkinitfs"
    chroot_exec "echo 'features=\"${features}\"' > /etc/mkinitfs/mkinitfs.conf"

    # Regenerate the initramfs for the exact installed kernel flavor so the
    # filename (initramfs-${kernel_type}) matches what the bootloader expects.
    # The linux-* apk trigger already created one with the default config;
    # this rebuilds it with the features above.
    try "Generating initramfs" \
        chroot_exec "kver=\$(basename /lib/modules/*-${kernel_type} 2>/dev/null); \
            mkinitfs -o /boot/initramfs-${kernel_type} \${kver:-\$(uname -r)}"

    einfo "Kernel installed"
}

# --- Networking ---

install_networking() {
    einfo "Installing networking..."

    # D-Bus is a hard dependency of NetworkManager (and elogind/polkit later).
    # It must be installed and enabled regardless of desktop choice, and the
    # OpenRC init script lives in the dbus-openrc subpackage on modern Alpine.
    apk_install "Installing D-Bus" dbus dbus-openrc
    chroot_exec "rc-update add dbus default" 2>/dev/null || true

    # NetworkManager: the OpenRC init script and Wi-Fi backend live in separate
    # subpackages. networkmanager-wifi pulls wpa_supplicant. Without these,
    # `rc-update add networkmanager` silently has no init script and Wi-Fi
    # laptops have no connectivity on first boot.
    apk_install "Installing NetworkManager" \
        networkmanager networkmanager-openrc networkmanager-wifi \
        networkmanager-tui wpa_supplicant

    # Enable NetworkManager via OpenRC
    try "Enabling NetworkManager" \
        chroot_exec "rc-update add networkmanager default"

    # NetworkManager manages interfaces itself; keep the `networking` service
    # only for the loopback interface.
    chroot_exec "cat > /etc/network/interfaces << 'NETEOF'
auto lo
iface lo inet loopback
NETEOF" 2>/dev/null || true
    chroot_exec "rc-update add networking boot" 2>/dev/null || true

    einfo "Networking configured"
}

# --- Users ---

system_create_users() {
    einfo "Creating users..."

    # Install shadow for full useradd/chpasswd (busybox versions are limited)
    apk_install "Installing shadow" shadow

    # Set root password (chpasswd -e avoids exposing hash in process list)
    if [[ -n "${ROOT_PASSWORD_HASH:-}" ]]; then
        echo "root:${ROOT_PASSWORD_HASH}" > "${MOUNTPOINT}/tmp/.pw_hash_$$"
        try "Setting root password" \
            chroot_exec "chpasswd -e < /tmp/.pw_hash_$$ && rm -f /tmp/.pw_hash_$$"
        rm -f "${MOUNTPOINT}/tmp/.pw_hash_$$" 2>/dev/null
    fi

    # Create regular user
    if [[ -n "${USERNAME:-}" ]]; then
        local groups="${USER_GROUPS:-wheel,audio,video,input,plugdev,seat}"

        # Filter out groups that don't exist on the target system
        local valid_groups=""
        local g
        IFS=',' read -ra _groups <<< "${groups}"
        for g in "${_groups[@]}"; do
            if chroot_exec "getent group ${g}" &>/dev/null; then
                valid_groups+="${valid_groups:+,}${g}"
            else
                # Try to create common groups that may not exist yet
                case "${g}" in
                    plugdev|input|seat)
                        chroot_exec "addgroup ${g}" 2>/dev/null || true
                        valid_groups+="${valid_groups:+,}${g}"
                        ;;
                    *)
                        ewarn "Group '${g}' does not exist, skipping"
                        ;;
                esac
            fi
        done
        groups="${valid_groups:-wheel}"

        # Install bash and use it as login shell
        apk_install_if_available bash

        local user_shell="/bin/sh"
        if chroot_exec "test -x /bin/bash" 2>/dev/null; then
            user_shell="/bin/bash"
        fi

        try "Creating user ${USERNAME}" \
            chroot_exec "useradd -m -G ${groups} -s ${user_shell} ${USERNAME}"

        if [[ -n "${USER_PASSWORD_HASH:-}" ]]; then
            echo "${USERNAME}:${USER_PASSWORD_HASH}" > "${MOUNTPOINT}/tmp/.pw_hash_$$"
            try "Setting user password" \
                chroot_exec "chpasswd -e < /tmp/.pw_hash_$$ && rm -f /tmp/.pw_hash_$$"
            rm -f "${MOUNTPOINT}/tmp/.pw_hash_$$" 2>/dev/null
        fi

        # Setup doas (Alpine uses doas by default, lighter than sudo)
        apk_install_if_available doas
        chroot_exec "mkdir -p /etc/doas.d"
        chroot_exec "echo 'permit persist :wheel' > /etc/doas.d/wheel.conf"
        chroot_exec "chmod 0640 /etc/doas.d/wheel.conf"

        einfo "User ${USERNAME} created with groups: ${groups}"
    fi

    # SSH
    if [[ "${ENABLE_SSH:-no}" == "yes" ]]; then
        apk_install "Installing OpenSSH" openssh

        try "Enabling sshd" \
            chroot_exec "rc-update add sshd default"

        einfo "SSH server enabled"
    fi
}

# --- Device manager ---

# _setup_device_manager — eudev (udev) for desktops, mdev for headless.
# Running both mdev and eudev simultaneously corrupts device nodes, so the
# manager is selected exclusively. Desktops (libinput, DRM/KMS, GPU) need udev.
_setup_device_manager() {
    if [[ "${DESKTOP_ENV:-none}" != "none" ]]; then
        einfo "Configuring eudev device manager (desktop)..."
        apk_install "Installing eudev" eudev

        # eudev OpenRC scripts: udev/udev-trigger/udev-settle in sysinit,
        # udev-postmount in default. mdev must NOT be enabled alongside.
        chroot_exec "rc-update del mdev sysinit" 2>/dev/null || true
        chroot_exec "rc-update add udev sysinit" 2>/dev/null || true
        chroot_exec "rc-update add udev-trigger sysinit" 2>/dev/null || true
        chroot_exec "rc-update add udev-settle sysinit" 2>/dev/null || true
        chroot_exec "rc-update add udev-postmount default" 2>/dev/null || true
    else
        einfo "Configuring mdev device manager (headless)..."
        chroot_exec "rc-update add mdev sysinit" 2>/dev/null || true
    fi
}

# --- Finalization ---

system_finalize() {
    einfo "Finalizing system..."

    # Enable the core OpenRC runlevels.
    #
    # `apk add --root --initdb alpine-base` does NOT populate /etc/runlevels
    # (the official setup-disk/setup-alpine scripts do that). Without this an
    # otherwise-correct install boots degraded: no /etc/fstab mounts (ESP, /tmp),
    # no swap, no fsck, no entropy seeding. We replicate a stock Alpine layout.
    _rc_add() { chroot_exec "rc-update add $1 $2" 2>/dev/null || true; }

    # --- sysinit: device manager + early kernel plumbing ---
    # Device manager (eudev vs mdev) is configured in _setup_device_manager;
    # here we only add the manager-agnostic services.
    _rc_add devfs sysinit
    _rc_add dmesg sysinit
    _rc_add cgroups sysinit
    _rc_add hwdrivers sysinit

    # --- boot: mount fstab, swap, fsck, clock, modules, entropy ---
    _rc_add modules boot
    _rc_add sysctl boot
    _rc_add hostname boot
    _rc_add bootmisc boot
    _rc_add hwclock boot   # RTC-backed; swclock is for RTC-less boards only
    _rc_add seedrng boot
    _rc_add fsck boot
    _rc_add root boot
    _rc_add localmount boot      # mounts ESP, /tmp and extra fstab entries
    if [[ "${SWAP_TYPE:-}" == "partition" || "${SWAP_TYPE:-}" == "zram" ]]; then
        _rc_add swap boot
    fi
    apk_install_if_available busybox-syslogd
    _rc_add syslog boot
    _rc_add klogd boot

    # --- default: late services ---
    _rc_add netmount default
    _rc_add local default
    apk_install_if_available acpid
    _rc_add acpid default
    apk_install_if_available cronie
    _rc_add crond default

    # --- shutdown ---
    _rc_add mount-ro shutdown
    _rc_add killprocs shutdown
    _rc_add savecache shutdown

    # Device manager: eudev (udev) for desktops, mdev otherwise.
    _setup_device_manager

    # Generate machine-id (dbus is installed in install_networking).
    chroot_exec "dbus-uuidgen --ensure=/var/lib/dbus/machine-id" 2>/dev/null || true
    chroot_exec "dbus-uuidgen --ensure=/etc/machine-id" 2>/dev/null || true

    # Set correct date/time inside chroot if possible
    chroot_exec "hwclock --systohc" 2>/dev/null || true

    # Install bundled gum binary (useful for dotfiles/scripts)
    if [[ -x "${GUM_CACHE_DIR:-/tmp/alpine-gum}/gum" ]]; then
        cp "${GUM_CACHE_DIR}/gum" "${MOUNTPOINT}/usr/local/bin/gum" 2>/dev/null && \
            chmod +x "${MOUNTPOINT}/usr/local/bin/gum" && \
            einfo "Installed gum to /usr/local/bin/gum"
    elif [[ -f "${DATA_DIR:-}/gum.tar.gz" ]]; then
        local _gum_tmp
        _gum_tmp=$(mktemp -d)
        if tar xzf "${DATA_DIR}/gum.tar.gz" -C "${_gum_tmp}" 2>/dev/null; then
            local _gum_bin
            _gum_bin=$(find "${_gum_tmp}" -name "gum" -type f | head -1)
            if [[ -n "${_gum_bin}" ]]; then
                cp "${_gum_bin}" "${MOUNTPOINT}/usr/local/bin/gum"
                chmod +x "${MOUNTPOINT}/usr/local/bin/gum"
                einfo "Installed gum to /usr/local/bin/gum"
            fi
        fi
        rm -rf "${_gum_tmp}"
    fi

    # Clean up installer artifacts from target disk
    rm -rf "${MOUNTPOINT}${CHECKPOINT_DIR_SUFFIX}" 2>/dev/null || true
    rm -f "${MOUNTPOINT}/tmp/$(basename "${CONFIG_FILE}")" 2>/dev/null || true

    einfo "System finalization complete"
}
